### PR TITLE
Palomar: Add alt text to ES Doc Text field

### PR DESCRIPTION
**Pull request by jcsalterego**
Adds alt text for images to the ES doc's text field.

For example:

Given
```
Text: i should buy a boat
Image 1 Alt: cat thinking i should buy a boat
Image 2 Alt: cat at the insurance office getting boat insurance
```

Then
```
ES Doc Text: i should buy a boat cat thinking i should buy a boat cat at the insurance office getting boat insurance
```

### CODE REVIEW

**Review by whyrusleeping — APPROVED** [review]
Oh great idea, Thanks @jcsalterego !

**Comment by jcsalterego** [comment]
I can't seem to reproduce the test failure locally. Is it a related failure?

**Comment by jcsalterego** [comment]
It passed in this CI build FWIW https://github.com/jcsalterego/indigo/actions/runs/5662477475/job/15342470966

**Comment by whyrusleeping** [comment]
Yeah, thats a known flaky test. I need to figure out how to deal with that better...

**Comment by whyrusleeping** [comment]
rerunning the tests to try and get a clean merge

**Comment by jcsalterego** [comment]
Would love to know if there's anything I can do to help this get merged!

**Comment by jcsalterego** [comment]
I assume this is on hold for a larger mapping change and task to reindex all posts?

**Comment by jcsalterego** [comment]
> I assume this is on hold for a larger mapping change and task to reindex all posts?

I think this would be good to get merged and online, even if it's only for a portion of the data (no backfill), and pending some larger changes in the schema.

**Comment by bnewbold** [comment]
This feature should be working in prod as of the past couple weeks, as part of a broader refactor of how we index posts. It took forever!

I'm going to close this PR; if the feature isn't working the way you expect, please re-open an issue. Sorry to leave you hanging on this helpful PR for so long, and thanks again for the contribution.

**Comment by jcsalterego** [comment]
@bnewbold The big search refactor looks great and was worth the wait. Thanks!

**Pull request closed without merging**
