### PR TITLE
fix build

### PR DESCRIPTION
**Pull request by mattn**
Compiling util always fail.

```
github.com/ipfs/go-ipfs-blockstore
# github.com/ipfs/go-ipfs-blockstore
../../../go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.2.1-0.20220823165003-9904c18f1d0a/blockstore.go:36:38: undefined: ipld.Block
```

### CODE REVIEW

**Comment by mattn** [comment]
Closed by https://github.com/bluesky-social/indigo/commit/56d29448c0312bd41c1a6418dc175e531a4dee62

**Comment by mattn** [comment]
image

**Comment by mattn** [comment]
I confirmed fixed.

**Comment by bnewbold** [comment]
:relieved:

**Comment by bnewbold** [comment]
Assuming this is fixed, as you confirmed above, so re-closing.

**Comment by mattn** [comment]
FYI: https://staging.bsky.app/profile/dholms.xyz/post/3jsfpvgdm222w

**Pull request closed without merging**
