### PR TITLE
Support facet tags for search

### PR DESCRIPTION
**Pull request by ericvolp12**

### CODE REVIEW

**Comment by Zero3K** [comment]
Does this fix https://github.com/bluesky-social/indigo/issues/581?

**Comment by ericvolp12** [comment]
This is the start of getting hashtag searching for the tag field within a post (the actual hashtag implementation).

Not gonna merge anything here for a bit but just poking around with the query constructor for now.

**Comment by Zero3K** [comment]
Tag field? Like Tumblr?

**Comment by ericvolp12** [comment]
The post record type supports tags (like hastags) in Facets as well as in an additional field in the post record, these aren't fully implemented in our client yet but will be eventually - https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json#L50

**Comment by Zero3K** [comment]
Or will it just be like how Twitter does it?

**Pull request merged**
