### PR TITLE
fix nil pointer exception on creating account, when relay is self-hosted

### LINKED ISSUE #704: bug: self-hosting relay raises nil pointer exception on creating account in PDS.
the exception is caused by below part (line 363).
c.Client is cared nil only when c.Host is *.bsky.network by line 352,  but not in else clause(self-hosting relay).

https://github.com/bluesky-social/indigo/blob/7d1235931bd3537c1a1f63ffca73bca4bdd632c2/cmd/bigsky/main.go#L350-L365

c.Client should be created when it is nil regardless c.Host value, as below:

```patch
                } else {
+                       if c.Client == nil {
+                               c.Client = util.RobustHTTPClient()
+                       }
                        // Generic PDS timeout
                        c.Client.Timeout = time.Minute * 1                        
```

### PR DESCRIPTION
**Pull request by itaru2622**
close #704

### CODE REVIEW

**Comment by itaru2622** [comment]
this PR fix the em-bug by #696

**Comment by itaru2622** [comment]
@ericvolp12 @bnewbold could you review this PR please.

**Comment by bnewbold** [comment]
Looks like a good catch!

Instead of duplicating the nil check and assignment in both conditional branches of the `if` statement, could you move it just above? Like:

```diff
diff --git a/cmd/bigsky/main.go b/cmd/bigsky/main.go
index 33e60a0b..d0961ecc 100644
--- a/cmd/bigsky/main.go
+++ b/cmd/bigsky/main.go
@@ -348,10 +348,10 @@ func runBigsky(cctx *cli.Context) error {
 
        rlskip := cctx.String("bsky-social-rate-limit-skip")
        ix.ApplyPDSClientSettings = func(c *xrpc.Client) {
+               if c.Client == nil {
+                       c.Client = util.RobustHTTPClient()
+               }
                if strings.HasSuffix(c.Host, ".bsky.network") {
-                       if c.Client == nil {
-                               c.Client = util.RobustHTTPClient()
-                       }
                        c.Client.Timeout = time.Minute * 30
                        if rlskip != "" {
                                c.Headers = map[string]string{
```

**Comment by itaru2622** [comment]
@bnewbold thank you for your review. I followed your comment and pushed update.

**Comment by itaru2622** [comment]
hmm am I getting in trouble on pushing update to PR branch?

even I pushed update in PR branch, this github PR page didn't detects new commit for "Files changed TAB".

I mean:
even I confirmed that my PR branch has latest code with my update followed your comment,
and the commit hash in above conversation log shows latest code with my update, 
"File changed TAB" keeps showing old code without my update.

I met this trouble first time, and not sure how I can fix it yet. even I pushed with force again, situation was not changed.
I hope this trouble is just matter on UI of github pages and not gives bad affect on code merging process.

**Pull request merged**
