### PR TITLE
Lex refactor branch ("last big breaking lexicon changes")

### PR DESCRIPTION
**Pull request by whyrusleeping**
Working towards #83 mostly

bigsky and laputa compile, havent tested them yet. Still a fair emount left to do

### CODE REVIEW

**Comment by bnewbold** [comment]
I guess I spoke too soon: the tests pass locally for me (including in a fresh checkout), but not in CI. It is possible that golang 1.19 vs. 1.20 is the issue (I've updated on my laptop; this PR hasn't landed: https://github.com/bluesky-social/indigo/pull/91). But more likely some timing issue.

**Comment by bnewbold** [comment]
Some more progress, all tests are passing now. BGS interop with typescript lex-refactor branch is not working yet.

I hacked in the subscription changes pretty quickly, I suspect that more refactoring might be needed in BGS, repomgr, etc. The previous `RepoAppend` object could be both a `repo_append` or a `rebase`, based on the `Event` field value; now the different event types are different structs. Maybe we should pass around entire `XRPCStreamEvent` structs? This is just a vague impression, I just "got things to compile" without digging in to how the rebase vs. commit code paths work.

Tweaked a couple lexgen things relating to required-but-nullable fields. This is only implemented on structs for now, not handler function signatures or query params.

Created an issue to track post-refactor follow-ups: https://github.com/bluesky-social/indigo/issues/95

I have hit a couple different errors trying to do BGS interop with typescript implementation. One error looks like:

```
2023-03-29T21:16:33.850-0700	ERROR	indexer	indexer/crawler.go:160	failed to perform repo crawl of "did:plc:lzkaig7u5entvhqgr4cgabwm": importing fetched repo (curHead: bafyreia7y77ta5i3sazxkkpfmjl5j2adznebxjbps4odgmryrl2v3qffji): process new repo (current head: bafyreia7y77ta5i3sazxkkpfmjl5j2adznebxjbps4odgmryrl2v3qffji): walkTree: can only handle dag-cbor objects in repos (bafkreif6df2wrudglcyzdcx5qcjvv6e6lmipfzghvdzxscl5klgbu4lu6y is 85):
```

I think that is the indexer code breaking on the new CID links in records, which in the case of blobs are "raw" CID pointers to file bytes (not dag-cbor multicodec). The only other current use of the `cid-link` datatype is in repo subscription objects, but in the future there might be more CIDs in records pointing to either dag-cbor (in local or remote repos), or raw CIDs (pointing to arbitrary content).

Another error is:

```
2023-03-29T21:50:03.697-0700	ERROR	bgs	bgs/fedmgr.go:168	failed handling event from "localhost:2583" (252): handle user event failed: signature check failed: invalid signature
```

I'm not sure what the deal is with that. We have an existing test in `testing/sig_test.go` for basic signature validation.

New users don't seem to get picked up (or at least logged) by BGS; labelmaker event consumers sees them and ignores.

**Comment by bnewbold** [comment]
Ah, as a hint, also seeing the signature failure against typescript when using 'main' branch on both.

**Comment by whyrusleeping** [comment]
Got the embed/union issue figured out. That test still isnt passing yet but its better.

**Pull request merged**
