### PR TITLE
update cborgen to fix nil vs empty slice issue

### PR DESCRIPTION
**Pull request by whyrusleeping**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
cborgen changes from this PR: https://github.com/whyrusleeping/cbor-gen/pull/88

**Review by ericvolp12 — APPROVED** [review]
LGTM

**Comment by bnewbold** [comment]
@whyrusleeping small but you should run `make fmt` (dumb one-line tweak) and `go mod tidy` (removes unused `cbor-gen` versions from go.sum) before merging

**Comment by bnewbold** [comment]
also, looks like this rolls in some lexicon updates (lexgen), assume that is intentional

**Pull request merged**
