### PR TITLE
cherry pick rainbow account pass-through fix

### PR DESCRIPTION
**Pull request by bnewbold**

### CODE REVIEW

**Review by brianolson — APPROVED** [review]

**Review by brianolson — APPROVED** [review]

**Comment by brianolson** [comment]
redundant? already merged to main in 07de0a0518463b6f233df571f82f581d0e9772b5

**Comment by ericvolp12** [comment]
This is a cherry picked PR so the build in this PR is on top of the original Rainbow deploy without any of the later changes. We needed a fresh build without the intervening work to run in prod so we wanna keep this alive until we move off this image.

**Comment by ericvolp12** [comment]
I don't believe we've done a Rainbow deploy since. We're running `598831998dd4c5812900bad8f0085edf352f8aaf` right now.

**Comment by ericvolp12** [comment]
We want the changes in this PR merged because it has the `requestCrawl` passthrough stuff that isn't in main yet. I think we need to figure out how to merge this.

**Comment by brianolson** [comment]
done in #883

**Pull request closed without merging**
